#!/bin/sh

current=`cat /sys/class/backlight/gmux_backlight/brightness`
if [ "$1" = "up" ]; then
    max=`cat /sys/class/backlight/gmux_backlight/max_brightness`
    next=$((current+100))
    if [ $next -lt $max ]; then
        echo $next > /sys/class/backlight/gmux_backlight/brightness
    fi 
elif [ "$1" = "down" ]; then
    next=$((current-100))
    if [ $next -gt 0 ]; then
        echo $next > /sys/class/backlight/gmux_backlight/brightness
    fi 
else
    echo "Unrecognized option. Expected + or - as command line argument"
fi
