#!/bin/sh

if [ $# -eq 0 ]; then
    echo "Usage: monitor-action [FILE|DIRECTORY] ""COMMAND"""
    echo "Watch a FILE or DIRECTORY for changes. Whenever a change occurs, execute the supplied COMMAND"
    exit 1
fi
FORMAT=$(echo -e "\033[1;33m%w%f\033[0m written")
while true; do
    inotifywait -qre close_write --format "$FORMAT" $1
    echo "Executing command: " "$2"
    $2
done
